version: '3.1' 

services:
    http-ip-list-creator:
        restart: always
        build:
            context: ./        
        expose:
            - 8080           
        environment:        
            - HTTPIPLISTCREATOR_HTTP_PORT=8080
            - HTTPIPLISTCREATOR_DB_USER=blacklistuser
            - HTTPIPLISTCREATOR_DB_PASSWORD=verrysecurepassword
            - HTTPIPLISTCREATOR_DB_NAME=blacklistdb
            - HTTPIPLISTCREATOR_DB_HOST=supercluster.example.com
            - HTTPIPLISTCREATOR_DB_PORT=3306
            - HTTPIPLISTCREATOR_DB_TABLE=bannedIPs
            - HTTPIPLISTCREATOR_DB_COLUMN=ip
